/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionTokenRespDTO model module.
 * @module model/ActionTokenRespDTO
 * @version 1.0.0
 */
class ActionTokenRespDTO {
    /**
     * Constructs a new <code>ActionTokenRespDTO</code>.
     * @alias module:model/ActionTokenRespDTO
     */
    constructor() { 
        
        ActionTokenRespDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionTokenRespDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionTokenRespDTO} obj Optional instance to populate.
     * @return {module:model/ActionTokenRespDTO} The populated <code>ActionTokenRespDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionTokenRespDTO();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('recoveryQuestion')) {
                obj['recoveryQuestion'] = ApiClient.convertToType(data['recoveryQuestion'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
ActionTokenRespDTO.prototype['token'] = undefined;

/**
 * @member {Number} recoveryQuestion
 */
ActionTokenRespDTO.prototype['recoveryQuestion'] = undefined;






export default ActionTokenRespDTO;

