/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlertRespDTO model module.
 * @module model/AlertRespDTO
 * @version 1.0.3
 */
class AlertRespDTO {
    /**
     * Constructs a new <code>AlertRespDTO</code>.
     * @alias module:model/AlertRespDTO
     */
    constructor() { 
        
        AlertRespDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AlertRespDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlertRespDTO} obj Optional instance to populate.
     * @return {module:model/AlertRespDTO} The populated <code>AlertRespDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertRespDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('alertId')) {
                obj['alertId'] = ApiClient.convertToType(data['alertId'], 'String');
            }
            if (data.hasOwnProperty('alertType')) {
                obj['alertType'] = ApiClient.convertToType(data['alertType'], 'String');
            }
            if (data.hasOwnProperty('creationDate')) {
                obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
            }
            if (data.hasOwnProperty('dataSource')) {
                obj['dataSource'] = ApiClient.convertToType(data['dataSource'], 'String');
            }
            if (data.hasOwnProperty('dateReported')) {
                obj['dateReported'] = ApiClient.convertToType(data['dateReported'], 'Date');
            }
            if (data.hasOwnProperty('reportingFrequency')) {
                obj['reportingFrequency'] = ApiClient.convertToType(data['reportingFrequency'], 'String');
            }
            if (data.hasOwnProperty('institutionType')) {
                obj['institutionType'] = ApiClient.convertToType(data['institutionType'], 'String');
            }
            if (data.hasOwnProperty('institutionName')) {
                obj['institutionName'] = ApiClient.convertToType(data['institutionName'], 'String');
            }
            if (data.hasOwnProperty('inquiryIntent')) {
                obj['inquiryIntent'] = ApiClient.convertToType(data['inquiryIntent'], 'String');
            }
            if (data.hasOwnProperty('inquiryType')) {
                obj['inquiryType'] = ApiClient.convertToType(data['inquiryType'], 'String');
            }
            if (data.hasOwnProperty('endUserText')) {
                obj['endUserText'] = ApiClient.convertToType(data['endUserText'], 'String');
            }
            if (data.hasOwnProperty('institutionAddressLine1')) {
                obj['institutionAddressLine1'] = ApiClient.convertToType(data['institutionAddressLine1'], 'String');
            }
            if (data.hasOwnProperty('institutionAddressLine2')) {
                obj['institutionAddressLine2'] = ApiClient.convertToType(data['institutionAddressLine2'], 'String');
            }
            if (data.hasOwnProperty('institutionCity')) {
                obj['institutionCity'] = ApiClient.convertToType(data['institutionCity'], 'String');
            }
            if (data.hasOwnProperty('institutionState')) {
                obj['institutionState'] = ApiClient.convertToType(data['institutionState'], 'String');
            }
            if (data.hasOwnProperty('institutionPostalCode')) {
                obj['institutionPostalCode'] = ApiClient.convertToType(data['institutionPostalCode'], 'String');
            }
            if (data.hasOwnProperty('institutionPhoneNumber')) {
                obj['institutionPhoneNumber'] = ApiClient.convertToType(data['institutionPhoneNumber'], 'String');
            }
            if (data.hasOwnProperty('postedDuringMaintenancePeriod')) {
                obj['postedDuringMaintenancePeriod'] = ApiClient.convertToType(data['postedDuringMaintenancePeriod'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
AlertRespDTO.prototype['id'] = undefined;

/**
 * @member {String} alertId
 */
AlertRespDTO.prototype['alertId'] = undefined;

/**
 * @member {String} alertType
 */
AlertRespDTO.prototype['alertType'] = undefined;

/**
 * @member {Date} creationDate
 */
AlertRespDTO.prototype['creationDate'] = undefined;

/**
 * @member {String} dataSource
 */
AlertRespDTO.prototype['dataSource'] = undefined;

/**
 * @member {Date} dateReported
 */
AlertRespDTO.prototype['dateReported'] = undefined;

/**
 * @member {String} reportingFrequency
 */
AlertRespDTO.prototype['reportingFrequency'] = undefined;

/**
 * @member {String} institutionType
 */
AlertRespDTO.prototype['institutionType'] = undefined;

/**
 * @member {String} institutionName
 */
AlertRespDTO.prototype['institutionName'] = undefined;

/**
 * @member {String} inquiryIntent
 */
AlertRespDTO.prototype['inquiryIntent'] = undefined;

/**
 * @member {String} inquiryType
 */
AlertRespDTO.prototype['inquiryType'] = undefined;

/**
 * @member {String} endUserText
 */
AlertRespDTO.prototype['endUserText'] = undefined;

/**
 * @member {String} institutionAddressLine1
 */
AlertRespDTO.prototype['institutionAddressLine1'] = undefined;

/**
 * @member {String} institutionAddressLine2
 */
AlertRespDTO.prototype['institutionAddressLine2'] = undefined;

/**
 * @member {String} institutionCity
 */
AlertRespDTO.prototype['institutionCity'] = undefined;

/**
 * @member {String} institutionState
 */
AlertRespDTO.prototype['institutionState'] = undefined;

/**
 * @member {String} institutionPostalCode
 */
AlertRespDTO.prototype['institutionPostalCode'] = undefined;

/**
 * @member {String} institutionPhoneNumber
 */
AlertRespDTO.prototype['institutionPhoneNumber'] = undefined;

/**
 * @member {Boolean} postedDuringMaintenancePeriod
 */
AlertRespDTO.prototype['postedDuringMaintenancePeriod'] = undefined;






export default AlertRespDTO;

