/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationContextClassLoaderParentUnnamedModuleClassLoader from './ApplicationContextClassLoaderParentUnnamedModuleClassLoader';
import ApplicationContextClassLoaderParentUnnamedModuleDescriptor from './ApplicationContextClassLoaderParentUnnamedModuleDescriptor';

/**
 * The ApplicationContextClassLoaderParentUnnamedModule model module.
 * @module model/ApplicationContextClassLoaderParentUnnamedModule
 * @version 1.0.0
 */
class ApplicationContextClassLoaderParentUnnamedModule {
    /**
     * Constructs a new <code>ApplicationContextClassLoaderParentUnnamedModule</code>.
     * @alias module:model/ApplicationContextClassLoaderParentUnnamedModule
     */
    constructor() { 
        
        ApplicationContextClassLoaderParentUnnamedModule.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApplicationContextClassLoaderParentUnnamedModule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationContextClassLoaderParentUnnamedModule} obj Optional instance to populate.
     * @return {module:model/ApplicationContextClassLoaderParentUnnamedModule} The populated <code>ApplicationContextClassLoaderParentUnnamedModule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationContextClassLoaderParentUnnamedModule();

            if (data.hasOwnProperty('layer')) {
                obj['layer'] = ApiClient.convertToType(data['layer'], Object);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('descriptor')) {
                obj['descriptor'] = ApplicationContextClassLoaderParentUnnamedModuleDescriptor.constructFromObject(data['descriptor']);
            }
            if (data.hasOwnProperty('classLoader')) {
                obj['classLoader'] = ApplicationContextClassLoaderParentUnnamedModuleClassLoader.constructFromObject(data['classLoader']);
            }
            if (data.hasOwnProperty('annotations')) {
                obj['annotations'] = ApiClient.convertToType(data['annotations'], [Object]);
            }
            if (data.hasOwnProperty('declaredAnnotations')) {
                obj['declaredAnnotations'] = ApiClient.convertToType(data['declaredAnnotations'], [Object]);
            }
            if (data.hasOwnProperty('named')) {
                obj['named'] = ApiClient.convertToType(data['named'], 'Boolean');
            }
            if (data.hasOwnProperty('packages')) {
                obj['packages'] = ApiClient.convertToType(data['packages'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} layer
 */
ApplicationContextClassLoaderParentUnnamedModule.prototype['layer'] = undefined;

/**
 * @member {String} name
 */
ApplicationContextClassLoaderParentUnnamedModule.prototype['name'] = undefined;

/**
 * @member {module:model/ApplicationContextClassLoaderParentUnnamedModuleDescriptor} descriptor
 */
ApplicationContextClassLoaderParentUnnamedModule.prototype['descriptor'] = undefined;

/**
 * @member {module:model/ApplicationContextClassLoaderParentUnnamedModuleClassLoader} classLoader
 */
ApplicationContextClassLoaderParentUnnamedModule.prototype['classLoader'] = undefined;

/**
 * @member {Array.<Object>} annotations
 */
ApplicationContextClassLoaderParentUnnamedModule.prototype['annotations'] = undefined;

/**
 * @member {Array.<Object>} declaredAnnotations
 */
ApplicationContextClassLoaderParentUnnamedModule.prototype['declaredAnnotations'] = undefined;

/**
 * @member {Boolean} named
 */
ApplicationContextClassLoaderParentUnnamedModule.prototype['named'] = undefined;

/**
 * @member {Array.<String>} packages
 */
ApplicationContextClassLoaderParentUnnamedModule.prototype['packages'] = undefined;






export default ApplicationContextClassLoaderParentUnnamedModule;

