/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationContextClassLoaderParentUnnamedModuleDescriptor model module.
 * @module model/ApplicationContextClassLoaderParentUnnamedModuleDescriptor
 * @version 1.0.0
 */
class ApplicationContextClassLoaderParentUnnamedModuleDescriptor {
    /**
     * Constructs a new <code>ApplicationContextClassLoaderParentUnnamedModuleDescriptor</code>.
     * @alias module:model/ApplicationContextClassLoaderParentUnnamedModuleDescriptor
     */
    constructor() { 
        
        ApplicationContextClassLoaderParentUnnamedModuleDescriptor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApplicationContextClassLoaderParentUnnamedModuleDescriptor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationContextClassLoaderParentUnnamedModuleDescriptor} obj Optional instance to populate.
     * @return {module:model/ApplicationContextClassLoaderParentUnnamedModuleDescriptor} The populated <code>ApplicationContextClassLoaderParentUnnamedModuleDescriptor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationContextClassLoaderParentUnnamedModuleDescriptor();

            if (data.hasOwnProperty('open')) {
                obj['open'] = ApiClient.convertToType(data['open'], 'Boolean');
            }
            if (data.hasOwnProperty('automatic')) {
                obj['automatic'] = ApiClient.convertToType(data['automatic'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} open
 */
ApplicationContextClassLoaderParentUnnamedModuleDescriptor.prototype['open'] = undefined;

/**
 * @member {Boolean} automatic
 */
ApplicationContextClassLoaderParentUnnamedModuleDescriptor.prototype['automatic'] = undefined;






export default ApplicationContextClassLoaderParentUnnamedModuleDescriptor;

