/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackages from './ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackages';

/**
 * The ApplicationContextClassLoaderParentUnnamedModuleClassLoader model module.
 * @module model/ApplicationContextClassLoaderParentUnnamedModuleClassLoader
 * @version 1.0.0
 */
class ApplicationContextClassLoaderParentUnnamedModuleClassLoader {
    /**
     * Constructs a new <code>ApplicationContextClassLoaderParentUnnamedModuleClassLoader</code>.
     * @alias module:model/ApplicationContextClassLoaderParentUnnamedModuleClassLoader
     */
    constructor() { 
        
        ApplicationContextClassLoaderParentUnnamedModuleClassLoader.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApplicationContextClassLoaderParentUnnamedModuleClassLoader</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationContextClassLoaderParentUnnamedModuleClassLoader} obj Optional instance to populate.
     * @return {module:model/ApplicationContextClassLoaderParentUnnamedModuleClassLoader} The populated <code>ApplicationContextClassLoaderParentUnnamedModuleClassLoader</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationContextClassLoaderParentUnnamedModuleClassLoader();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('defaultAssertionStatus')) {
                obj['defaultAssertionStatus'] = ApiClient.convertToType(data['defaultAssertionStatus'], 'Boolean');
            }
            if (data.hasOwnProperty('registeredAsParallelCapable')) {
                obj['registeredAsParallelCapable'] = ApiClient.convertToType(data['registeredAsParallelCapable'], 'Boolean');
            }
            if (data.hasOwnProperty('definedPackages')) {
                obj['definedPackages'] = ApiClient.convertToType(data['definedPackages'], [ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackages]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
ApplicationContextClassLoaderParentUnnamedModuleClassLoader.prototype['name'] = undefined;

/**
 * @member {Boolean} defaultAssertionStatus
 */
ApplicationContextClassLoaderParentUnnamedModuleClassLoader.prototype['defaultAssertionStatus'] = undefined;

/**
 * @member {Boolean} registeredAsParallelCapable
 */
ApplicationContextClassLoaderParentUnnamedModuleClassLoader.prototype['registeredAsParallelCapable'] = undefined;

/**
 * @member {Array.<module:model/ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackages>} definedPackages
 */
ApplicationContextClassLoaderParentUnnamedModuleClassLoader.prototype['definedPackages'] = undefined;






export default ApplicationContextClassLoaderParentUnnamedModuleClassLoader;

