/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CodeDescriptionReport from './CodeDescriptionReport';
import MoneyReport from './MoneyReport';

/**
 * The BankruptcyReport model module.
 * @module model/BankruptcyReport
 * @version 1.0.1
 */
class BankruptcyReport {
    /**
     * Constructs a new <code>BankruptcyReport</code>.
     * @alias module:model/BankruptcyReport
     */
    constructor() { 
        
        BankruptcyReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BankruptcyReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BankruptcyReport} obj Optional instance to populate.
     * @return {module:model/BankruptcyReport} The populated <code>BankruptcyReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BankruptcyReport();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('filedDate')) {
                obj['filedDate'] = ApiClient.convertToType(data['filedDate'], 'Date');
            }
            if (data.hasOwnProperty('reportedDate')) {
                obj['reportedDate'] = ApiClient.convertToType(data['reportedDate'], 'Date');
            }
            if (data.hasOwnProperty('referenceNumber')) {
                obj['referenceNumber'] = ApiClient.convertToType(data['referenceNumber'], 'String');
            }
            if (data.hasOwnProperty('dispositionStatus')) {
                obj['dispositionStatus'] = CodeDescriptionReport.constructFromObject(data['dispositionStatus']);
            }
            if (data.hasOwnProperty('courtName')) {
                obj['courtName'] = ApiClient.convertToType(data['courtName'], 'String');
            }
            if (data.hasOwnProperty('liability')) {
                obj['liability'] = MoneyReport.constructFromObject(data['liability']);
            }
            if (data.hasOwnProperty('exemptAmount')) {
                obj['exemptAmount'] = MoneyReport.constructFromObject(data['exemptAmount']);
            }
            if (data.hasOwnProperty('assetAmount')) {
                obj['assetAmount'] = MoneyReport.constructFromObject(data['assetAmount']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
BankruptcyReport.prototype['id'] = undefined;

/**
 * @member {Date} filedDate
 */
BankruptcyReport.prototype['filedDate'] = undefined;

/**
 * @member {Date} reportedDate
 */
BankruptcyReport.prototype['reportedDate'] = undefined;

/**
 * @member {String} referenceNumber
 */
BankruptcyReport.prototype['referenceNumber'] = undefined;

/**
 * @member {module:model/CodeDescriptionReport} dispositionStatus
 */
BankruptcyReport.prototype['dispositionStatus'] = undefined;

/**
 * @member {String} courtName
 */
BankruptcyReport.prototype['courtName'] = undefined;

/**
 * @member {module:model/MoneyReport} liability
 */
BankruptcyReport.prototype['liability'] = undefined;

/**
 * @member {module:model/MoneyReport} exemptAmount
 */
BankruptcyReport.prototype['exemptAmount'] = undefined;

/**
 * @member {module:model/MoneyReport} assetAmount
 */
BankruptcyReport.prototype['assetAmount'] = undefined;






export default BankruptcyReport;

