/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangeRecoveryReqDTO model module.
 * @module model/ChangeRecoveryReqDTO
 * @version 1.0.0
 */
class ChangeRecoveryReqDTO {
    /**
     * Constructs a new <code>ChangeRecoveryReqDTO</code>.
     * @alias module:model/ChangeRecoveryReqDTO
     * @param recoveryQuestion {Number} 
     * @param recoveryAnswer {String} 
     * @param oldRecoveryAnswer {String} 
     * @param token {String} 
     */
    constructor(recoveryQuestion, recoveryAnswer, oldRecoveryAnswer, token) { 
        
        ChangeRecoveryReqDTO.initialize(this, recoveryQuestion, recoveryAnswer, oldRecoveryAnswer, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, recoveryQuestion, recoveryAnswer, oldRecoveryAnswer, token) { 
        obj['recoveryQuestion'] = recoveryQuestion;
        obj['recoveryAnswer'] = recoveryAnswer;
        obj['oldRecoveryAnswer'] = oldRecoveryAnswer;
        obj['token'] = token;
    }

    /**
     * Constructs a <code>ChangeRecoveryReqDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeRecoveryReqDTO} obj Optional instance to populate.
     * @return {module:model/ChangeRecoveryReqDTO} The populated <code>ChangeRecoveryReqDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeRecoveryReqDTO();

            if (data.hasOwnProperty('recoveryQuestion')) {
                obj['recoveryQuestion'] = ApiClient.convertToType(data['recoveryQuestion'], 'Number');
            }
            if (data.hasOwnProperty('recoveryAnswer')) {
                obj['recoveryAnswer'] = ApiClient.convertToType(data['recoveryAnswer'], 'String');
            }
            if (data.hasOwnProperty('oldRecoveryAnswer')) {
                obj['oldRecoveryAnswer'] = ApiClient.convertToType(data['oldRecoveryAnswer'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} recoveryQuestion
 */
ChangeRecoveryReqDTO.prototype['recoveryQuestion'] = undefined;

/**
 * @member {String} recoveryAnswer
 */
ChangeRecoveryReqDTO.prototype['recoveryAnswer'] = undefined;

/**
 * @member {String} oldRecoveryAnswer
 */
ChangeRecoveryReqDTO.prototype['oldRecoveryAnswer'] = undefined;

/**
 * @member {String} token
 */
ChangeRecoveryReqDTO.prototype['token'] = undefined;






export default ChangeRecoveryReqDTO;

