/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CloseAccountReqDTO model module.
 * @module model/CloseAccountReqDTO
 * @version 1.0.0
 */
class CloseAccountReqDTO {
    /**
     * Constructs a new <code>CloseAccountReqDTO</code>.
     * @alias module:model/CloseAccountReqDTO
     * @param recoveryAnswer {String} 
     * @param token {String} 
     */
    constructor(recoveryAnswer, token) { 
        
        CloseAccountReqDTO.initialize(this, recoveryAnswer, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, recoveryAnswer, token) { 
        obj['recoveryAnswer'] = recoveryAnswer;
        obj['token'] = token;
    }

    /**
     * Constructs a <code>CloseAccountReqDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloseAccountReqDTO} obj Optional instance to populate.
     * @return {module:model/CloseAccountReqDTO} The populated <code>CloseAccountReqDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloseAccountReqDTO();

            if (data.hasOwnProperty('recoveryAnswer')) {
                obj['recoveryAnswer'] = ApiClient.convertToType(data['recoveryAnswer'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} recoveryAnswer
 */
CloseAccountReqDTO.prototype['recoveryAnswer'] = undefined;

/**
 * @member {String} token
 */
CloseAccountReqDTO.prototype['token'] = undefined;






export default CloseAccountReqDTO;

