/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CollectionItem model module.
 * @module model/CollectionItem
 * @version 1.0.0
 */
class CollectionItem {
    /**
     * Constructs a new <code>CollectionItem</code>.
     * @alias module:model/CollectionItem
     */
    constructor() { 
        
        CollectionItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CollectionItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CollectionItem} obj Optional instance to populate.
     * @return {module:model/CollectionItem} The populated <code>CollectionItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectionItem();

            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('reportedDate')) {
                obj['reportedDate'] = ApiClient.convertToType(data['reportedDate'], 'Date');
            }
            if (data.hasOwnProperty('assignedDate')) {
                obj['assignedDate'] = ApiClient.convertToType(data['assignedDate'], 'Date');
            }
            if (data.hasOwnProperty('agencyClient')) {
                obj['agencyClient'] = ApiClient.convertToType(data['agencyClient'], 'String');
            }
            if (data.hasOwnProperty('orginalAmountOwed')) {
                obj['orginalAmountOwed'] = ApiClient.convertToType(data['orginalAmountOwed'], Object);
            }
            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('accountDesignatorCode')) {
                obj['accountDesignatorCode'] = ApiClient.convertToType(data['accountDesignatorCode'], 'String');
            }
            if (data.hasOwnProperty('balanceDate')) {
                obj['balanceDate'] = ApiClient.convertToType(data['balanceDate'], 'Date');
            }
            if (data.hasOwnProperty('statusDate')) {
                obj['statusDate'] = ApiClient.convertToType(data['statusDate'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CollectionItem.ProviderEnum} provider
 */
CollectionItem.prototype['provider'] = undefined;

/**
 * @member {String} id
 */
CollectionItem.prototype['id'] = undefined;

/**
 * @member {Date} reportedDate
 */
CollectionItem.prototype['reportedDate'] = undefined;

/**
 * @member {Date} assignedDate
 */
CollectionItem.prototype['assignedDate'] = undefined;

/**
 * @member {String} agencyClient
 */
CollectionItem.prototype['agencyClient'] = undefined;

/**
 * @member {Object} orginalAmountOwed
 */
CollectionItem.prototype['orginalAmountOwed'] = undefined;

/**
 * @member {String} accountNumber
 */
CollectionItem.prototype['accountNumber'] = undefined;

/**
 * @member {module:model/CollectionItem.AccountDesignatorCodeEnum} accountDesignatorCode
 */
CollectionItem.prototype['accountDesignatorCode'] = undefined;

/**
 * @member {Date} balanceDate
 */
CollectionItem.prototype['balanceDate'] = undefined;

/**
 * @member {Date} statusDate
 */
CollectionItem.prototype['statusDate'] = undefined;

/**
 * @member {module:model/CollectionItem.StatusEnum} status
 */
CollectionItem.prototype['status'] = undefined;

/**
 * @member {Object} amount
 */
CollectionItem.prototype['amount'] = undefined;





/**
 * Allowed values for the <code>provider</code> property.
 * @enum {String}
 * @readonly
 */
CollectionItem['ProviderEnum'] = {

    /**
     * value: "EFX"
     * @const
     */
    "EFX": "EFX",

    /**
     * value: "TU"
     * @const
     */
    "TU": "TU",

    /**
     * value: "EXP"
     * @const
     */
    "EXP": "EXP",

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN"
};


/**
 * Allowed values for the <code>accountDesignatorCode</code> property.
 * @enum {String}
 * @readonly
 */
CollectionItem['AccountDesignatorCodeEnum'] = {

    /**
     * value: "AUTHORIZED_USER"
     * @const
     */
    "AUTHORIZED_USER": "AUTHORIZED_USER",

    /**
     * value: "CO_MAKER"
     * @const
     */
    "CO_MAKER": "CO_MAKER",

    /**
     * value: "DECEASED"
     * @const
     */
    "DECEASED": "DECEASED",

    /**
     * value: "INDIVIDUAL_ACCOUNT"
     * @const
     */
    "INDIVIDUAL_ACCOUNT": "INDIVIDUAL_ACCOUNT",

    /**
     * value: "JOINT_ACCOUNT"
     * @const
     */
    "JOINT_ACCOUNT": "JOINT_ACCOUNT",

    /**
     * value: "MAKER"
     * @const
     */
    "MAKER": "MAKER",

    /**
     * value: "ON_BEHALF_OF_ANOTHER_PERSON"
     * @const
     */
    "ON_BEHALF_OF_ANOTHER_PERSON": "ON_BEHALF_OF_ANOTHER_PERSON",

    /**
     * value: "SHARED"
     * @const
     */
    "SHARED": "SHARED",

    /**
     * value: "TERMINATED"
     * @const
     */
    "TERMINATED": "TERMINATED",

    /**
     * value: "UNDESIGNATED"
     * @const
     */
    "UNDESIGNATED": "UNDESIGNATED"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CollectionItem['StatusEnum'] = {

    /**
     * value: "CLOSED"
     * @const
     */
    "CLOSED": "CLOSED",

    /**
     * value: "FROZEN"
     * @const
     */
    "FROZEN": "FROZEN",

    /**
     * value: "OPEN"
     * @const
     */
    "OPEN": "OPEN",

    /**
     * value: "REFINANCED"
     * @const
     */
    "REFINANCED": "REFINANCED",

    /**
     * value: "TRANSFERRED"
     * @const
     */
    "TRANSFERRED": "TRANSFERRED",

    /**
     * value: "ACCOUNT_DISPUTED"
     * @const
     */
    "ACCOUNT_DISPUTED": "ACCOUNT_DISPUTED",

    /**
     * value: "ADJUSTMENT"
     * @const
     */
    "ADJUSTMENT": "ADJUSTMENT",

    /**
     * value: "CHECKED"
     * @const
     */
    "CHECKED": "CHECKED",

    /**
     * value: "FINANCIAL_COUNSELOR"
     * @const
     */
    "FINANCIAL_COUNSELOR": "FINANCIAL_COUNSELOR",

    /**
     * value: "IN_BANKRUPTCY"
     * @const
     */
    "IN_BANKRUPTCY": "IN_BANKRUPTCY",

    /**
     * value: "NEW_LISTING"
     * @const
     */
    "NEW_LISTING": "NEW_LISTING",

    /**
     * value: "OTHER"
     * @const
     */
    "OTHER": "OTHER",

    /**
     * value: "PAID"
     * @const
     */
    "PAID": "PAID",

    /**
     * value: "PAYMENT"
     * @const
     */
    "PAYMENT": "PAYMENT",

    /**
     * value: "SETTLED"
     * @const
     */
    "SETTLED": "SETTLED",

    /**
     * value: "STATUS_UNKNOWN"
     * @const
     */
    "STATUS_UNKNOWN": "STATUS_UNKNOWN",

    /**
     * value: "SUPPRESS_COLLECTION"
     * @const
     */
    "SUPPRESS_COLLECTION": "SUPPRESS_COLLECTION",

    /**
     * value: "UNPAID"
     * @const
     */
    "UNPAID": "UNPAID",

    /**
     * value: "UNSETTLED"
     * @const
     */
    "UNSETTLED": "UNSETTLED",

    /**
     * value: "WAGE_EARNER"
     * @const
     */
    "WAGE_EARNER": "WAGE_EARNER"
};



export default CollectionItem;

