/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CountryReport model module.
 * @module model/CountryReport
 * @version 1.0.1
 */
class CountryReport {
    /**
     * Constructs a new <code>CountryReport</code>.
     * @alias module:model/CountryReport
     */
    constructor() { 
        
        CountryReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CountryReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CountryReport} obj Optional instance to populate.
     * @return {module:model/CountryReport} The populated <code>CountryReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CountryReport();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
CountryReport.prototype['code'] = undefined;

/**
 * @member {String} name
 */
CountryReport.prototype['name'] = undefined;






export default CountryReport;

