/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreditScoreLoanRiskRangeScore model module.
 * @module model/CreditScoreLoanRiskRangeScore
 * @version 1.0.0
 */
class CreditScoreLoanRiskRangeScore {
    /**
     * Constructs a new <code>CreditScoreLoanRiskRangeScore</code>.
     * @alias module:model/CreditScoreLoanRiskRangeScore
     */
    constructor() { 
        
        CreditScoreLoanRiskRangeScore.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditScoreLoanRiskRangeScore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditScoreLoanRiskRangeScore} obj Optional instance to populate.
     * @return {module:model/CreditScoreLoanRiskRangeScore} The populated <code>CreditScoreLoanRiskRangeScore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditScoreLoanRiskRangeScore();

            if (data.hasOwnProperty('low')) {
                obj['low'] = ApiClient.convertToType(data['low'], 'Number');
            }
            if (data.hasOwnProperty('high')) {
                obj['high'] = ApiClient.convertToType(data['high'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} low
 */
CreditScoreLoanRiskRangeScore.prototype['low'] = undefined;

/**
 * @member {Number} high
 */
CreditScoreLoanRiskRangeScore.prototype['high'] = undefined;

/**
 * @member {String} name
 */
CreditScoreLoanRiskRangeScore.prototype['name'] = undefined;






export default CreditScoreLoanRiskRangeScore;

