/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreditReportProviderViewReport from './CreditReportProviderViewReport';

/**
 * The CreditReportReport model module.
 * @module model/CreditReportReport
 * @version 1.0.3
 */
class CreditReportReport {
    /**
     * Constructs a new <code>CreditReportReport</code>.
     * @alias module:model/CreditReportReport
     */
    constructor() { 
        
        CreditReportReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditReportReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditReportReport} obj Optional instance to populate.
     * @return {module:model/CreditReportReport} The populated <code>CreditReportReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditReportReport();

            if (data.hasOwnProperty('providerViews')) {
                obj['providerViews'] = ApiClient.convertToType(data['providerViews'], [CreditReportProviderViewReport]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('reportType')) {
                obj['reportType'] = ApiClient.convertToType(data['reportType'], 'String');
            }
            if (data.hasOwnProperty('generatedDate')) {
                obj['generatedDate'] = ApiClient.convertToType(data['generatedDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/CreditReportProviderViewReport>} providerViews
 */
CreditReportReport.prototype['providerViews'] = undefined;

/**
 * @member {String} id
 */
CreditReportReport.prototype['id'] = undefined;

/**
 * @member {module:model/CreditReportReport.ReportTypeEnum} reportType
 */
CreditReportReport.prototype['reportType'] = undefined;

/**
 * @member {Date} generatedDate
 */
CreditReportReport.prototype['generatedDate'] = undefined;





/**
 * Allowed values for the <code>reportType</code> property.
 * @enum {String}
 * @readonly
 */
CreditReportReport['ReportTypeEnum'] = {

    /**
     * value: "US_EFX"
     * @const
     */
    "EFX": "US_EFX",

    /**
     * value: "US_3B"
     * @const
     */
    "3B": "US_3B"
};



export default CreditReportReport;

