/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MoneyReport from './MoneyReport';

/**
 * The CreditReportSummaryAccountsReport model module.
 * @module model/CreditReportSummaryAccountsReport
 * @version 1.0.3
 */
class CreditReportSummaryAccountsReport {
    /**
     * Constructs a new <code>CreditReportSummaryAccountsReport</code>.
     * @alias module:model/CreditReportSummaryAccountsReport
     */
    constructor() { 
        
        CreditReportSummaryAccountsReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditReportSummaryAccountsReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditReportSummaryAccountsReport} obj Optional instance to populate.
     * @return {module:model/CreditReportSummaryAccountsReport} The populated <code>CreditReportSummaryAccountsReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditReportSummaryAccountsReport();

            if (data.hasOwnProperty('balance')) {
                obj['balance'] = MoneyReport.constructFromObject(data['balance']);
            }
            if (data.hasOwnProperty('creditLimit')) {
                obj['creditLimit'] = MoneyReport.constructFromObject(data['creditLimit']);
            }
            if (data.hasOwnProperty('available')) {
                obj['available'] = MoneyReport.constructFromObject(data['available']);
            }
            if (data.hasOwnProperty('monthlyPaymentAmount')) {
                obj['monthlyPaymentAmount'] = MoneyReport.constructFromObject(data['monthlyPaymentAmount']);
            }
            if (data.hasOwnProperty('debtToCreditRatio')) {
                obj['debtToCreditRatio'] = ApiClient.convertToType(data['debtToCreditRatio'], 'Number');
            }
            if (data.hasOwnProperty('totalAccounts')) {
                obj['totalAccounts'] = ApiClient.convertToType(data['totalAccounts'], 'Number');
            }
            if (data.hasOwnProperty('totalNegativeAccounts')) {
                obj['totalNegativeAccounts'] = ApiClient.convertToType(data['totalNegativeAccounts'], 'Number');
            }
            if (data.hasOwnProperty('totalAccountsWithBalance')) {
                obj['totalAccountsWithBalance'] = ApiClient.convertToType(data['totalAccountsWithBalance'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MoneyReport} balance
 */
CreditReportSummaryAccountsReport.prototype['balance'] = undefined;

/**
 * @member {module:model/MoneyReport} creditLimit
 */
CreditReportSummaryAccountsReport.prototype['creditLimit'] = undefined;

/**
 * @member {module:model/MoneyReport} available
 */
CreditReportSummaryAccountsReport.prototype['available'] = undefined;

/**
 * @member {module:model/MoneyReport} monthlyPaymentAmount
 */
CreditReportSummaryAccountsReport.prototype['monthlyPaymentAmount'] = undefined;

/**
 * @member {Number} debtToCreditRatio
 */
CreditReportSummaryAccountsReport.prototype['debtToCreditRatio'] = undefined;

/**
 * @member {Number} totalAccounts
 */
CreditReportSummaryAccountsReport.prototype['totalAccounts'] = undefined;

/**
 * @member {Number} totalNegativeAccounts
 */
CreditReportSummaryAccountsReport.prototype['totalNegativeAccounts'] = undefined;

/**
 * @member {Number} totalAccountsWithBalance
 */
CreditReportSummaryAccountsReport.prototype['totalAccountsWithBalance'] = undefined;






export default CreditReportSummaryAccountsReport;

