/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreditScoreHistoryProviderViewScore from './CreditScoreHistoryProviderViewScore';

/**
 * The CreditScoreHistoryScore model module.
 * @module model/CreditScoreHistoryScore
 * @version 1.0.3
 */
class CreditScoreHistoryScore {
    /**
     * Constructs a new <code>CreditScoreHistoryScore</code>.
     * @alias module:model/CreditScoreHistoryScore
     */
    constructor() { 
        
        CreditScoreHistoryScore.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditScoreHistoryScore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditScoreHistoryScore} obj Optional instance to populate.
     * @return {module:model/CreditScoreHistoryScore} The populated <code>CreditScoreHistoryScore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditScoreHistoryScore();

            if (data.hasOwnProperty('generatedDate')) {
                obj['generatedDate'] = ApiClient.convertToType(data['generatedDate'], 'Date');
            }
            if (data.hasOwnProperty('scoreType')) {
                obj['scoreType'] = ApiClient.convertToType(data['scoreType'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('scoreModel')) {
                obj['scoreModel'] = ApiClient.convertToType(data['scoreModel'], 'String');
            }
            if (data.hasOwnProperty('providerViews')) {
                obj['providerViews'] = ApiClient.convertToType(data['providerViews'], [CreditScoreHistoryProviderViewScore]);
            }
        }
        return obj;
    }


}

/**
 * @member {Date} generatedDate
 */
CreditScoreHistoryScore.prototype['generatedDate'] = undefined;

/**
 * @member {module:model/CreditScoreHistoryScore.ScoreTypeEnum} scoreType
 */
CreditScoreHistoryScore.prototype['scoreType'] = undefined;

/**
 * @member {String} id
 */
CreditScoreHistoryScore.prototype['id'] = undefined;

/**
 * @member {module:model/CreditScoreHistoryScore.ScoreModelEnum} scoreModel
 */
CreditScoreHistoryScore.prototype['scoreModel'] = undefined;

/**
 * @member {Array.<module:model/CreditScoreHistoryProviderViewScore>} providerViews
 */
CreditScoreHistoryScore.prototype['providerViews'] = undefined;





/**
 * Allowed values for the <code>scoreType</code> property.
 * @enum {String}
 * @readonly
 */
CreditScoreHistoryScore['ScoreTypeEnum'] = {

    /**
     * value: "US_EFX"
     * @const
     */
    "EFX": "US_EFX",

    /**
     * value: "US_3B"
     * @const
     */
    "3B": "US_3B"
};


/**
 * Allowed values for the <code>scoreModel</code> property.
 * @enum {String}
 * @readonly
 */
CreditScoreHistoryScore['ScoreModelEnum'] = {

    /**
     * value: "VANTAGE"
     * @const
     */
    "VANTAGE": "VANTAGE",

    /**
     * value: "ERS"
     * @const
     */
    "ERS": "ERS",

    /**
     * value: "FICO"
     * @const
     */
    "FICO": "FICO",

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN"
};



export default CreditScoreHistoryScore;

