/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InternationalAddressReport from './InternationalAddressReport';
import InternationalPhoneReport from './InternationalPhoneReport';

/**
 * The CreditReportProviderDisputeInformationReport model module.
 * @module model/CreditReportProviderDisputeInformationReport
 * @version 1.0.3
 */
class CreditReportProviderDisputeInformationReport {
    /**
     * Constructs a new <code>CreditReportProviderDisputeInformationReport</code>.
     * @alias module:model/CreditReportProviderDisputeInformationReport
     */
    constructor() { 
        
        CreditReportProviderDisputeInformationReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditReportProviderDisputeInformationReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditReportProviderDisputeInformationReport} obj Optional instance to populate.
     * @return {module:model/CreditReportProviderDisputeInformationReport} The populated <code>CreditReportProviderDisputeInformationReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditReportProviderDisputeInformationReport();

            if (data.hasOwnProperty('contactName')) {
                obj['contactName'] = ApiClient.convertToType(data['contactName'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = InternationalAddressReport.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = InternationalPhoneReport.constructFromObject(data['phone']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} contactName
 */
CreditReportProviderDisputeInformationReport.prototype['contactName'] = undefined;

/**
 * @member {module:model/InternationalAddressReport} address
 */
CreditReportProviderDisputeInformationReport.prototype['address'] = undefined;

/**
 * @member {module:model/InternationalPhoneReport} phone
 */
CreditReportProviderDisputeInformationReport.prototype['phone'] = undefined;






export default CreditReportProviderDisputeInformationReport;

