/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreditScoreReasonReport model module.
 * @module model/CreditScoreReasonReport
 * @version 1.0.3
 */
class CreditScoreReasonReport {
    /**
     * Constructs a new <code>CreditScoreReasonReport</code>.
     * @alias module:model/CreditScoreReasonReport
     */
    constructor() { 
        
        CreditScoreReasonReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditScoreReasonReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditScoreReasonReport} obj Optional instance to populate.
     * @return {module:model/CreditScoreReasonReport} The populated <code>CreditScoreReasonReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditScoreReasonReport();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('creditScoreFactorEffect')) {
                obj['creditScoreFactorEffect'] = ApiClient.convertToType(data['creditScoreFactorEffect'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
CreditScoreReasonReport.prototype['code'] = undefined;

/**
 * @member {String} description
 */
CreditScoreReasonReport.prototype['description'] = undefined;

/**
 * @member {module:model/CreditScoreReasonReport.CreditScoreFactorEffectEnum} creditScoreFactorEffect
 */
CreditScoreReasonReport.prototype['creditScoreFactorEffect'] = undefined;





/**
 * Allowed values for the <code>creditScoreFactorEffect</code> property.
 * @enum {String}
 * @readonly
 */
CreditScoreReasonReport['CreditScoreFactorEffectEnum'] = {

    /**
     * value: "HELPING"
     * @const
     */
    "HELPING": "HELPING",

    /**
     * value: "HURTING"
     * @const
     */
    "HURTING": "HURTING",

    /**
     * value: "NEUTRAL"
     * @const
     */
    "NEUTRAL": "NEUTRAL"
};



export default CreditScoreReasonReport;

