/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CollectionItemReport from './CollectionItemReport';
import ConsumerStatementReport from './ConsumerStatementReport';
import CreditReportAccountReport from './CreditReportAccountReport';
import CreditReportSummaryReport from './CreditReportSummaryReport';
import InquiryReport from './InquiryReport';
import PublicRecordsReport from './PublicRecordsReport';

/**
 * The CreditReportProviderViewReport model module.
 * @module model/CreditReportProviderViewReport
 * @version 1.0.0
 */
class CreditReportProviderViewReport {
    /**
     * Constructs a new <code>CreditReportProviderViewReport</code>.
     * @alias module:model/CreditReportProviderViewReport
     */
    constructor() { 
        
        CreditReportProviderViewReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditReportProviderViewReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditReportProviderViewReport} obj Optional instance to populate.
     * @return {module:model/CreditReportProviderViewReport} The populated <code>CreditReportProviderViewReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditReportProviderViewReport();

            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = CreditReportSummaryReport.constructFromObject(data['summary']);
            }
            if (data.hasOwnProperty('revolvingAccounts')) {
                obj['revolvingAccounts'] = ApiClient.convertToType(data['revolvingAccounts'], [CreditReportAccountReport]);
            }
            if (data.hasOwnProperty('mortgageAccounts')) {
                obj['mortgageAccounts'] = ApiClient.convertToType(data['mortgageAccounts'], [CreditReportAccountReport]);
            }
            if (data.hasOwnProperty('installmentAccounts')) {
                obj['installmentAccounts'] = ApiClient.convertToType(data['installmentAccounts'], [CreditReportAccountReport]);
            }
            if (data.hasOwnProperty('otherAccounts')) {
                obj['otherAccounts'] = ApiClient.convertToType(data['otherAccounts'], [CreditReportAccountReport]);
            }
            if (data.hasOwnProperty('inquiries')) {
                obj['inquiries'] = ApiClient.convertToType(data['inquiries'], [InquiryReport]);
            }
            if (data.hasOwnProperty('consumerStatements')) {
                obj['consumerStatements'] = ApiClient.convertToType(data['consumerStatements'], [ConsumerStatementReport]);
            }
            if (data.hasOwnProperty('publicRecords')) {
                obj['publicRecords'] = PublicRecordsReport.constructFromObject(data['publicRecords']);
            }
            if (data.hasOwnProperty('collections')) {
                obj['collections'] = ApiClient.convertToType(data['collections'], [CollectionItemReport]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CreditReportProviderViewReport.ProviderEnum} provider
 */
CreditReportProviderViewReport.prototype['provider'] = undefined;

/**
 * @member {module:model/CreditReportSummaryReport} summary
 */
CreditReportProviderViewReport.prototype['summary'] = undefined;

/**
 * @member {Array.<module:model/CreditReportAccountReport>} revolvingAccounts
 */
CreditReportProviderViewReport.prototype['revolvingAccounts'] = undefined;

/**
 * @member {Array.<module:model/CreditReportAccountReport>} mortgageAccounts
 */
CreditReportProviderViewReport.prototype['mortgageAccounts'] = undefined;

/**
 * @member {Array.<module:model/CreditReportAccountReport>} installmentAccounts
 */
CreditReportProviderViewReport.prototype['installmentAccounts'] = undefined;

/**
 * @member {Array.<module:model/CreditReportAccountReport>} otherAccounts
 */
CreditReportProviderViewReport.prototype['otherAccounts'] = undefined;

/**
 * @member {Array.<module:model/InquiryReport>} inquiries
 */
CreditReportProviderViewReport.prototype['inquiries'] = undefined;

/**
 * @member {Array.<module:model/ConsumerStatementReport>} consumerStatements
 */
CreditReportProviderViewReport.prototype['consumerStatements'] = undefined;

/**
 * @member {module:model/PublicRecordsReport} publicRecords
 */
CreditReportProviderViewReport.prototype['publicRecords'] = undefined;

/**
 * @member {Array.<module:model/CollectionItemReport>} collections
 */
CreditReportProviderViewReport.prototype['collections'] = undefined;





/**
 * Allowed values for the <code>provider</code> property.
 * @enum {String}
 * @readonly
 */
CreditReportProviderViewReport['ProviderEnum'] = {

    /**
     * value: "EFX"
     * @const
     */
    "EFX": "EFX",

    /**
     * value: "TU"
     * @const
     */
    "TU": "TU",

    /**
     * value: "EXP"
     * @const
     */
    "EXP": "EXP",

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN"
};



export default CreditReportProviderViewReport;

