/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CollectionItem from './CollectionItem';
import ConsumerStatement from './ConsumerStatement';
import CreditReportAccount from './CreditReportAccount';
import Inquiry from './Inquiry';

/**
 * The CreditReportProviderView model module.
 * @module model/CreditReportProviderView
 * @version 1.0.0
 */
class CreditReportProviderView {
    /**
     * Constructs a new <code>CreditReportProviderView</code>.
     * @alias module:model/CreditReportProviderView
     */
    constructor() { 
        
        CreditReportProviderView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditReportProviderView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditReportProviderView} obj Optional instance to populate.
     * @return {module:model/CreditReportProviderView} The populated <code>CreditReportProviderView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditReportProviderView();

            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], Object);
            }
            if (data.hasOwnProperty('revolvingAccounts')) {
                obj['revolvingAccounts'] = ApiClient.convertToType(data['revolvingAccounts'], [CreditReportAccount]);
            }
            if (data.hasOwnProperty('mortgageAccounts')) {
                obj['mortgageAccounts'] = ApiClient.convertToType(data['mortgageAccounts'], [CreditReportAccount]);
            }
            if (data.hasOwnProperty('installmentAccounts')) {
                obj['installmentAccounts'] = ApiClient.convertToType(data['installmentAccounts'], [CreditReportAccount]);
            }
            if (data.hasOwnProperty('otherAccounts')) {
                obj['otherAccounts'] = ApiClient.convertToType(data['otherAccounts'], [CreditReportAccount]);
            }
            if (data.hasOwnProperty('inquiries')) {
                obj['inquiries'] = ApiClient.convertToType(data['inquiries'], [Inquiry]);
            }
            if (data.hasOwnProperty('consumerStatements')) {
                obj['consumerStatements'] = ApiClient.convertToType(data['consumerStatements'], [ConsumerStatement]);
            }
            if (data.hasOwnProperty('publicRecords')) {
                obj['publicRecords'] = ApiClient.convertToType(data['publicRecords'], Object);
            }
            if (data.hasOwnProperty('collections')) {
                obj['collections'] = ApiClient.convertToType(data['collections'], [CollectionItem]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CreditReportProviderView.ProviderEnum} provider
 */
CreditReportProviderView.prototype['provider'] = undefined;

/**
 * @member {Object} summary
 */
CreditReportProviderView.prototype['summary'] = undefined;

/**
 * @member {Array.<module:model/CreditReportAccount>} revolvingAccounts
 */
CreditReportProviderView.prototype['revolvingAccounts'] = undefined;

/**
 * @member {Array.<module:model/CreditReportAccount>} mortgageAccounts
 */
CreditReportProviderView.prototype['mortgageAccounts'] = undefined;

/**
 * @member {Array.<module:model/CreditReportAccount>} installmentAccounts
 */
CreditReportProviderView.prototype['installmentAccounts'] = undefined;

/**
 * @member {Array.<module:model/CreditReportAccount>} otherAccounts
 */
CreditReportProviderView.prototype['otherAccounts'] = undefined;

/**
 * @member {Array.<module:model/Inquiry>} inquiries
 */
CreditReportProviderView.prototype['inquiries'] = undefined;

/**
 * @member {Array.<module:model/ConsumerStatement>} consumerStatements
 */
CreditReportProviderView.prototype['consumerStatements'] = undefined;

/**
 * @member {Object} publicRecords
 */
CreditReportProviderView.prototype['publicRecords'] = undefined;

/**
 * @member {Array.<module:model/CollectionItem>} collections
 */
CreditReportProviderView.prototype['collections'] = undefined;





/**
 * Allowed values for the <code>provider</code> property.
 * @enum {String}
 * @readonly
 */
CreditReportProviderView['ProviderEnum'] = {

    /**
     * value: "EFX"
     * @const
     */
    "EFX": "EFX",

    /**
     * value: "TU"
     * @const
     */
    "TU": "TU",

    /**
     * value: "EXP"
     * @const
     */
    "EXP": "EXP",

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN"
};



export default CreditReportProviderView;

