/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DirectChangeMobileReqDTO model module.
 * @module model/DirectChangeMobileReqDTO
 * @version 1.0.3
 */
class DirectChangeMobileReqDTO {
    /**
     * Constructs a new <code>DirectChangeMobileReqDTO</code>.
     * @alias module:model/DirectChangeMobileReqDTO
     */
    constructor() { 
        
        DirectChangeMobileReqDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DirectChangeMobileReqDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DirectChangeMobileReqDTO} obj Optional instance to populate.
     * @return {module:model/DirectChangeMobileReqDTO} The populated <code>DirectChangeMobileReqDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DirectChangeMobileReqDTO();

            if (data.hasOwnProperty('mobile')) {
                obj['mobile'] = ApiClient.convertToType(data['mobile'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} mobile
 */
DirectChangeMobileReqDTO.prototype['mobile'] = undefined;






export default DirectChangeMobileReqDTO;

