/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DirectUserRegReqDTO model module.
 * @module model/DirectUserRegReqDTO
 * @version 1.0.3
 */
class DirectUserRegReqDTO {
    /**
     * Constructs a new <code>DirectUserRegReqDTO</code>.
     * @alias module:model/DirectUserRegReqDTO
     * @param email {String} 
     * @param fname {String} 
     * @param lname {String} 
     */
    constructor(email, fname, lname) { 
        
        DirectUserRegReqDTO.initialize(this, email, fname, lname);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, fname, lname) { 
        obj['email'] = email;
        obj['fname'] = fname;
        obj['lname'] = lname;
    }

    /**
     * Constructs a <code>DirectUserRegReqDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DirectUserRegReqDTO} obj Optional instance to populate.
     * @return {module:model/DirectUserRegReqDTO} The populated <code>DirectUserRegReqDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DirectUserRegReqDTO();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('mobile')) {
                obj['mobile'] = ApiClient.convertToType(data['mobile'], 'String');
            }
            if (data.hasOwnProperty('fname')) {
                obj['fname'] = ApiClient.convertToType(data['fname'], 'String');
            }
            if (data.hasOwnProperty('lname')) {
                obj['lname'] = ApiClient.convertToType(data['lname'], 'String');
            }
            if (data.hasOwnProperty('smsMsg')) {
                obj['smsMsg'] = ApiClient.convertToType(data['smsMsg'], 'Boolean');
            }
            if (data.hasOwnProperty('emailMsg')) {
                obj['emailMsg'] = ApiClient.convertToType(data['emailMsg'], 'Boolean');
            }
            if (data.hasOwnProperty('pushMsg')) {
                obj['pushMsg'] = ApiClient.convertToType(data['pushMsg'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
DirectUserRegReqDTO.prototype['email'] = undefined;

/**
 * @member {String} mobile
 */
DirectUserRegReqDTO.prototype['mobile'] = undefined;

/**
 * @member {String} fname
 */
DirectUserRegReqDTO.prototype['fname'] = undefined;

/**
 * @member {String} lname
 */
DirectUserRegReqDTO.prototype['lname'] = undefined;

/**
 * @member {Boolean} smsMsg
 */
DirectUserRegReqDTO.prototype['smsMsg'] = undefined;

/**
 * @member {Boolean} emailMsg
 */
DirectUserRegReqDTO.prototype['emailMsg'] = undefined;

/**
 * @member {Boolean} pushMsg
 */
DirectUserRegReqDTO.prototype['pushMsg'] = undefined;






export default DirectUserRegReqDTO;

