/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EfxConfigRespDTO model module.
 * @module model/EfxConfigRespDTO
 * @version 1.0.3
 */
class EfxConfigRespDTO {
    /**
     * Constructs a new <code>EfxConfigRespDTO</code>.
     * @alias module:model/EfxConfigRespDTO
     */
    constructor() { 
        
        EfxConfigRespDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EfxConfigRespDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EfxConfigRespDTO} obj Optional instance to populate.
     * @return {module:model/EfxConfigRespDTO} The populated <code>EfxConfigRespDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EfxConfigRespDTO();

            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} secret
 */
EfxConfigRespDTO.prototype['secret'] = undefined;

/**
 * @member {String} id
 */
EfxConfigRespDTO.prototype['id'] = undefined;

/**
 * @member {String} url
 */
EfxConfigRespDTO.prototype['url'] = undefined;






export default EfxConfigRespDTO;

