/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Environment model module.
 * @module model/Environment
 * @version 1.0.0
 */
class Environment {
    /**
     * Constructs a new <code>Environment</code>.
     * @alias module:model/Environment
     */
    constructor() { 
        
        Environment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Environment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Environment} obj Optional instance to populate.
     * @return {module:model/Environment} The populated <code>Environment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Environment();

            if (data.hasOwnProperty('defaultProfiles')) {
                obj['defaultProfiles'] = ApiClient.convertToType(data['defaultProfiles'], ['String']);
            }
            if (data.hasOwnProperty('activeProfiles')) {
                obj['activeProfiles'] = ApiClient.convertToType(data['activeProfiles'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} defaultProfiles
 */
Environment.prototype['defaultProfiles'] = undefined;

/**
 * @member {Array.<String>} activeProfiles
 */
Environment.prototype['activeProfiles'] = undefined;






export default Environment;

