/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentityMobileRespDTO model module.
 * @module model/IdentityMobileRespDTO
 * @version 1.0.0
 */
class IdentityMobileRespDTO {
    /**
     * Constructs a new <code>IdentityMobileRespDTO</code>.
     * @alias module:model/IdentityMobileRespDTO
     */
    constructor() { 
        
        IdentityMobileRespDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdentityMobileRespDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentityMobileRespDTO} obj Optional instance to populate.
     * @return {module:model/IdentityMobileRespDTO} The populated <code>IdentityMobileRespDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentityMobileRespDTO();

            if (data.hasOwnProperty('mobile')) {
                obj['mobile'] = ApiClient.convertToType(data['mobile'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} mobile
 */
IdentityMobileRespDTO.prototype['mobile'] = undefined;

/**
 * @member {String} token
 */
IdentityMobileRespDTO.prototype['token'] = undefined;






export default IdentityMobileRespDTO;

