/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Question from './Question';

/**
 * The IdentityQuizDTO model module.
 * @module model/IdentityQuizDTO
 * @version 1.0.0
 */
class IdentityQuizDTO {
    /**
     * Constructs a new <code>IdentityQuizDTO</code>.
     * @alias module:model/IdentityQuizDTO
     */
    constructor() { 
        
        IdentityQuizDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdentityQuizDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentityQuizDTO} obj Optional instance to populate.
     * @return {module:model/IdentityQuizDTO} The populated <code>IdentityQuizDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentityQuizDTO();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('questions')) {
                obj['questions'] = ApiClient.convertToType(data['questions'], [Question]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
IdentityQuizDTO.prototype['key'] = undefined;

/**
 * @member {Number} id
 */
IdentityQuizDTO.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/Question>} questions
 */
IdentityQuizDTO.prototype['questions'] = undefined;






export default IdentityQuizDTO;

