/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Answer from './Answer';

/**
 * The IdentityQuizReqDTO model module.
 * @module model/IdentityQuizReqDTO
 * @version 1.0.0
 */
class IdentityQuizReqDTO {
    /**
     * Constructs a new <code>IdentityQuizReqDTO</code>.
     * @alias module:model/IdentityQuizReqDTO
     * @param key {String} 
     * @param id {Number} 
     */
    constructor(key, id) { 
        
        IdentityQuizReqDTO.initialize(this, key, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, id) { 
        obj['key'] = key;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>IdentityQuizReqDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentityQuizReqDTO} obj Optional instance to populate.
     * @return {module:model/IdentityQuizReqDTO} The populated <code>IdentityQuizReqDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentityQuizReqDTO();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('answers')) {
                obj['answers'] = ApiClient.convertToType(data['answers'], [Answer]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
IdentityQuizReqDTO.prototype['key'] = undefined;

/**
 * @member {Number} id
 */
IdentityQuizReqDTO.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/Answer>} answers
 */
IdentityQuizReqDTO.prototype['answers'] = undefined;






export default IdentityQuizReqDTO;

