/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CountryReport from './CountryReport';
import InternationalPhoneReport from './InternationalPhoneReport';

/**
 * The InternationalAddressReport model module.
 * @module model/InternationalAddressReport
 * @version 1.0.1
 */
class InternationalAddressReport {
    /**
     * Constructs a new <code>InternationalAddressReport</code>.
     * @alias module:model/InternationalAddressReport
     */
    constructor() { 
        
        InternationalAddressReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InternationalAddressReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InternationalAddressReport} obj Optional instance to populate.
     * @return {module:model/InternationalAddressReport} The populated <code>InternationalAddressReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InternationalAddressReport();

            if (data.hasOwnProperty('country')) {
                obj['country'] = CountryReport.constructFromObject(data['country']);
            }
            if (data.hasOwnProperty('line1')) {
                obj['line1'] = ApiClient.convertToType(data['line1'], 'String');
            }
            if (data.hasOwnProperty('line2')) {
                obj['line2'] = ApiClient.convertToType(data['line2'], 'String');
            }
            if (data.hasOwnProperty('line3')) {
                obj['line3'] = ApiClient.convertToType(data['line3'], 'String');
            }
            if (data.hasOwnProperty('line4')) {
                obj['line4'] = ApiClient.convertToType(data['line4'], 'String');
            }
            if (data.hasOwnProperty('line5')) {
                obj['line5'] = ApiClient.convertToType(data['line5'], 'String');
            }
            if (data.hasOwnProperty('firstReportedDate')) {
                obj['firstReportedDate'] = ApiClient.convertToType(data['firstReportedDate'], 'Date');
            }
            if (data.hasOwnProperty('lastReportedDate')) {
                obj['lastReportedDate'] = ApiClient.convertToType(data['lastReportedDate'], 'Date');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = InternationalPhoneReport.constructFromObject(data['phone']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CountryReport} country
 */
InternationalAddressReport.prototype['country'] = undefined;

/**
 * @member {String} line1
 */
InternationalAddressReport.prototype['line1'] = undefined;

/**
 * @member {String} line2
 */
InternationalAddressReport.prototype['line2'] = undefined;

/**
 * @member {String} line3
 */
InternationalAddressReport.prototype['line3'] = undefined;

/**
 * @member {String} line4
 */
InternationalAddressReport.prototype['line4'] = undefined;

/**
 * @member {String} line5
 */
InternationalAddressReport.prototype['line5'] = undefined;

/**
 * @member {Date} firstReportedDate
 */
InternationalAddressReport.prototype['firstReportedDate'] = undefined;

/**
 * @member {Date} lastReportedDate
 */
InternationalAddressReport.prototype['lastReportedDate'] = undefined;

/**
 * @member {module:model/InternationalPhoneReport} phone
 */
InternationalAddressReport.prototype['phone'] = undefined;






export default InternationalAddressReport;

