/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InternationalPhoneReport model module.
 * @module model/InternationalPhoneReport
 * @version 1.0.1
 */
class InternationalPhoneReport {
    /**
     * Constructs a new <code>InternationalPhoneReport</code>.
     * @alias module:model/InternationalPhoneReport
     */
    constructor() { 
        
        InternationalPhoneReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InternationalPhoneReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InternationalPhoneReport} obj Optional instance to populate.
     * @return {module:model/InternationalPhoneReport} The populated <code>InternationalPhoneReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InternationalPhoneReport();

            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('areaCode')) {
                obj['areaCode'] = ApiClient.convertToType(data['areaCode'], 'String');
            }
            if (data.hasOwnProperty('exchange')) {
                obj['exchange'] = ApiClient.convertToType(data['exchange'], 'String');
            }
            if (data.hasOwnProperty('extension')) {
                obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} countryCode
 */
InternationalPhoneReport.prototype['countryCode'] = undefined;

/**
 * @member {String} areaCode
 */
InternationalPhoneReport.prototype['areaCode'] = undefined;

/**
 * @member {String} exchange
 */
InternationalPhoneReport.prototype['exchange'] = undefined;

/**
 * @member {String} extension
 */
InternationalPhoneReport.prototype['extension'] = undefined;






export default InternationalPhoneReport;

