/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CodeDescriptionReport from './CodeDescriptionReport';
import MoneyReport from './MoneyReport';

/**
 * The JudgmentReport model module.
 * @module model/JudgmentReport
 * @version 1.0.0
 */
class JudgmentReport {
    /**
     * Constructs a new <code>JudgmentReport</code>.
     * @alias module:model/JudgmentReport
     */
    constructor() { 
        
        JudgmentReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JudgmentReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JudgmentReport} obj Optional instance to populate.
     * @return {module:model/JudgmentReport} The populated <code>JudgmentReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JudgmentReport();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('filedDate')) {
                obj['filedDate'] = ApiClient.convertToType(data['filedDate'], 'Date');
            }
            if (data.hasOwnProperty('reportedDate')) {
                obj['reportedDate'] = ApiClient.convertToType(data['reportedDate'], 'Date');
            }
            if (data.hasOwnProperty('courtName')) {
                obj['courtName'] = ApiClient.convertToType(data['courtName'], 'String');
            }
            if (data.hasOwnProperty('defendant')) {
                obj['defendant'] = ApiClient.convertToType(data['defendant'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = MoneyReport.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('caseDocumentNumber')) {
                obj['caseDocumentNumber'] = ApiClient.convertToType(data['caseDocumentNumber'], 'String');
            }
            if (data.hasOwnProperty('plaintiff')) {
                obj['plaintiff'] = ApiClient.convertToType(data['plaintiff'], 'String');
            }
            if (data.hasOwnProperty('verifiedDate')) {
                obj['verifiedDate'] = ApiClient.convertToType(data['verifiedDate'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = CodeDescriptionReport.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('satisfiedDate')) {
                obj['satisfiedDate'] = ApiClient.convertToType(data['satisfiedDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
JudgmentReport.prototype['id'] = undefined;

/**
 * @member {Date} filedDate
 */
JudgmentReport.prototype['filedDate'] = undefined;

/**
 * @member {Date} reportedDate
 */
JudgmentReport.prototype['reportedDate'] = undefined;

/**
 * @member {String} courtName
 */
JudgmentReport.prototype['courtName'] = undefined;

/**
 * @member {String} defendant
 */
JudgmentReport.prototype['defendant'] = undefined;

/**
 * @member {module:model/MoneyReport} amount
 */
JudgmentReport.prototype['amount'] = undefined;

/**
 * @member {String} caseDocumentNumber
 */
JudgmentReport.prototype['caseDocumentNumber'] = undefined;

/**
 * @member {String} plaintiff
 */
JudgmentReport.prototype['plaintiff'] = undefined;

/**
 * @member {Date} verifiedDate
 */
JudgmentReport.prototype['verifiedDate'] = undefined;

/**
 * @member {module:model/CodeDescriptionReport} status
 */
JudgmentReport.prototype['status'] = undefined;

/**
 * @member {Date} satisfiedDate
 */
JudgmentReport.prototype['satisfiedDate'] = undefined;






export default JudgmentReport;

