/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PasswordResetReqDTO model module.
 * @module model/PasswordResetReqDTO
 * @version 1.0.0
 */
class PasswordResetReqDTO {
    /**
     * Constructs a new <code>PasswordResetReqDTO</code>.
     * @alias module:model/PasswordResetReqDTO
     * @param token {String} 
     * @param recoveryAnswer {String} 
     * @param password {String} 
     */
    constructor(token, recoveryAnswer, password) { 
        
        PasswordResetReqDTO.initialize(this, token, recoveryAnswer, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token, recoveryAnswer, password) { 
        obj['token'] = token;
        obj['recoveryAnswer'] = recoveryAnswer;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>PasswordResetReqDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PasswordResetReqDTO} obj Optional instance to populate.
     * @return {module:model/PasswordResetReqDTO} The populated <code>PasswordResetReqDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PasswordResetReqDTO();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('recoveryAnswer')) {
                obj['recoveryAnswer'] = ApiClient.convertToType(data['recoveryAnswer'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
PasswordResetReqDTO.prototype['token'] = undefined;

/**
 * @member {String} recoveryAnswer
 */
PasswordResetReqDTO.prototype['recoveryAnswer'] = undefined;

/**
 * @member {String} password
 */
PasswordResetReqDTO.prototype['password'] = undefined;






export default PasswordResetReqDTO;

