/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentHistoryYear model module.
 * @module model/PaymentHistoryYear
 * @version 1.0.0
 */
class PaymentHistoryYear {
    /**
     * Constructs a new <code>PaymentHistoryYear</code>.
     * @alias module:model/PaymentHistoryYear
     */
    constructor() { 
        
        PaymentHistoryYear.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentHistoryYear</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentHistoryYear} obj Optional instance to populate.
     * @return {module:model/PaymentHistoryYear} The populated <code>PaymentHistoryYear</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentHistoryYear();

            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('january')) {
                obj['january'] = ApiClient.convertToType(data['january'], Object);
            }
            if (data.hasOwnProperty('february')) {
                obj['february'] = ApiClient.convertToType(data['february'], Object);
            }
            if (data.hasOwnProperty('march')) {
                obj['march'] = ApiClient.convertToType(data['march'], Object);
            }
            if (data.hasOwnProperty('april')) {
                obj['april'] = ApiClient.convertToType(data['april'], Object);
            }
            if (data.hasOwnProperty('may')) {
                obj['may'] = ApiClient.convertToType(data['may'], Object);
            }
            if (data.hasOwnProperty('june')) {
                obj['june'] = ApiClient.convertToType(data['june'], Object);
            }
            if (data.hasOwnProperty('july')) {
                obj['july'] = ApiClient.convertToType(data['july'], Object);
            }
            if (data.hasOwnProperty('august')) {
                obj['august'] = ApiClient.convertToType(data['august'], Object);
            }
            if (data.hasOwnProperty('september')) {
                obj['september'] = ApiClient.convertToType(data['september'], Object);
            }
            if (data.hasOwnProperty('october')) {
                obj['october'] = ApiClient.convertToType(data['october'], Object);
            }
            if (data.hasOwnProperty('november')) {
                obj['november'] = ApiClient.convertToType(data['november'], Object);
            }
            if (data.hasOwnProperty('december')) {
                obj['december'] = ApiClient.convertToType(data['december'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} year
 */
PaymentHistoryYear.prototype['year'] = undefined;

/**
 * @member {Object} january
 */
PaymentHistoryYear.prototype['january'] = undefined;

/**
 * @member {Object} february
 */
PaymentHistoryYear.prototype['february'] = undefined;

/**
 * @member {Object} march
 */
PaymentHistoryYear.prototype['march'] = undefined;

/**
 * @member {Object} april
 */
PaymentHistoryYear.prototype['april'] = undefined;

/**
 * @member {Object} may
 */
PaymentHistoryYear.prototype['may'] = undefined;

/**
 * @member {Object} june
 */
PaymentHistoryYear.prototype['june'] = undefined;

/**
 * @member {Object} july
 */
PaymentHistoryYear.prototype['july'] = undefined;

/**
 * @member {Object} august
 */
PaymentHistoryYear.prototype['august'] = undefined;

/**
 * @member {Object} september
 */
PaymentHistoryYear.prototype['september'] = undefined;

/**
 * @member {Object} october
 */
PaymentHistoryYear.prototype['october'] = undefined;

/**
 * @member {Object} november
 */
PaymentHistoryYear.prototype['november'] = undefined;

/**
 * @member {Object} december
 */
PaymentHistoryYear.prototype['december'] = undefined;






export default PaymentHistoryYear;

