/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentHistoryMonthReport from './PaymentHistoryMonthReport';

/**
 * The PaymentHistoryYearReport model module.
 * @module model/PaymentHistoryYearReport
 * @version 1.0.0
 */
class PaymentHistoryYearReport {
    /**
     * Constructs a new <code>PaymentHistoryYearReport</code>.
     * @alias module:model/PaymentHistoryYearReport
     */
    constructor() { 
        
        PaymentHistoryYearReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentHistoryYearReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentHistoryYearReport} obj Optional instance to populate.
     * @return {module:model/PaymentHistoryYearReport} The populated <code>PaymentHistoryYearReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentHistoryYearReport();

            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('january')) {
                obj['january'] = PaymentHistoryMonthReport.constructFromObject(data['january']);
            }
            if (data.hasOwnProperty('february')) {
                obj['february'] = PaymentHistoryMonthReport.constructFromObject(data['february']);
            }
            if (data.hasOwnProperty('march')) {
                obj['march'] = PaymentHistoryMonthReport.constructFromObject(data['march']);
            }
            if (data.hasOwnProperty('april')) {
                obj['april'] = PaymentHistoryMonthReport.constructFromObject(data['april']);
            }
            if (data.hasOwnProperty('may')) {
                obj['may'] = PaymentHistoryMonthReport.constructFromObject(data['may']);
            }
            if (data.hasOwnProperty('june')) {
                obj['june'] = PaymentHistoryMonthReport.constructFromObject(data['june']);
            }
            if (data.hasOwnProperty('july')) {
                obj['july'] = PaymentHistoryMonthReport.constructFromObject(data['july']);
            }
            if (data.hasOwnProperty('august')) {
                obj['august'] = PaymentHistoryMonthReport.constructFromObject(data['august']);
            }
            if (data.hasOwnProperty('september')) {
                obj['september'] = PaymentHistoryMonthReport.constructFromObject(data['september']);
            }
            if (data.hasOwnProperty('october')) {
                obj['october'] = PaymentHistoryMonthReport.constructFromObject(data['october']);
            }
            if (data.hasOwnProperty('november')) {
                obj['november'] = PaymentHistoryMonthReport.constructFromObject(data['november']);
            }
            if (data.hasOwnProperty('december')) {
                obj['december'] = PaymentHistoryMonthReport.constructFromObject(data['december']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} year
 */
PaymentHistoryYearReport.prototype['year'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} january
 */
PaymentHistoryYearReport.prototype['january'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} february
 */
PaymentHistoryYearReport.prototype['february'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} march
 */
PaymentHistoryYearReport.prototype['march'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} april
 */
PaymentHistoryYearReport.prototype['april'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} may
 */
PaymentHistoryYearReport.prototype['may'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} june
 */
PaymentHistoryYearReport.prototype['june'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} july
 */
PaymentHistoryYearReport.prototype['july'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} august
 */
PaymentHistoryYearReport.prototype['august'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} september
 */
PaymentHistoryYearReport.prototype['september'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} october
 */
PaymentHistoryYearReport.prototype['october'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} november
 */
PaymentHistoryYearReport.prototype['november'] = undefined;

/**
 * @member {module:model/PaymentHistoryMonthReport} december
 */
PaymentHistoryYearReport.prototype['december'] = undefined;






export default PaymentHistoryYearReport;

