/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonNameReport model module.
 * @module model/PersonNameReport
 * @version 1.0.1
 */
class PersonNameReport {
    /**
     * Constructs a new <code>PersonNameReport</code>.
     * @alias module:model/PersonNameReport
     */
    constructor() { 
        
        PersonNameReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonNameReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonNameReport} obj Optional instance to populate.
     * @return {module:model/PersonNameReport} The populated <code>PersonNameReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonNameReport();

            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('middleName')) {
                obj['middleName'] = ApiClient.convertToType(data['middleName'], 'String');
            }
            if (data.hasOwnProperty('suffix')) {
                obj['suffix'] = ApiClient.convertToType(data['suffix'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} lastName
 */
PersonNameReport.prototype['lastName'] = undefined;

/**
 * @member {String} firstName
 */
PersonNameReport.prototype['firstName'] = undefined;

/**
 * @member {String} middleName
 */
PersonNameReport.prototype['middleName'] = undefined;

/**
 * @member {String} suffix
 */
PersonNameReport.prototype['suffix'] = undefined;






export default PersonNameReport;

