/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScoreRange from './ScoreRange';
import ScoreReason from './ScoreReason';

/**
 * The ProviderView model module.
 * @module model/ProviderView
 * @version 1.0.0
 */
class ProviderView {
    /**
     * Constructs a new <code>ProviderView</code>.
     * @alias module:model/ProviderView
     */
    constructor() { 
        
        ProviderView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProviderView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProviderView} obj Optional instance to populate.
     * @return {module:model/ProviderView} The populated <code>ProviderView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProviderView();

            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('scoreRanges')) {
                obj['scoreRanges'] = ApiClient.convertToType(data['scoreRanges'], [ScoreRange]);
            }
            if (data.hasOwnProperty('loanRiskRanges')) {
                obj['loanRiskRanges'] = ApiClient.convertToType(data['loanRiskRanges'], [ScoreRange]);
            }
            if (data.hasOwnProperty('scoreReasons')) {
                obj['scoreReasons'] = ApiClient.convertToType(data['scoreReasons'], [ScoreReason]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} provider
 */
ProviderView.prototype['provider'] = undefined;

/**
 * @member {Number} score
 */
ProviderView.prototype['score'] = undefined;

/**
 * @member {Array.<module:model/ScoreRange>} scoreRanges
 */
ProviderView.prototype['scoreRanges'] = undefined;

/**
 * @member {Array.<module:model/ScoreRange>} loanRiskRanges
 */
ProviderView.prototype['loanRiskRanges'] = undefined;

/**
 * @member {Array.<module:model/ScoreReason>} scoreReasons
 */
ProviderView.prototype['scoreReasons'] = undefined;






export default ProviderView;

