/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BankruptcyReport from './BankruptcyReport';
import JudgmentReport from './JudgmentReport';
import LienReport from './LienReport';

/**
 * The PublicRecordsReport model module.
 * @module model/PublicRecordsReport
 * @version 1.0.3
 */
class PublicRecordsReport {
    /**
     * Constructs a new <code>PublicRecordsReport</code>.
     * @alias module:model/PublicRecordsReport
     */
    constructor() { 
        
        PublicRecordsReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PublicRecordsReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicRecordsReport} obj Optional instance to populate.
     * @return {module:model/PublicRecordsReport} The populated <code>PublicRecordsReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicRecordsReport();

            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('bankruptcies')) {
                obj['bankruptcies'] = ApiClient.convertToType(data['bankruptcies'], [BankruptcyReport]);
            }
            if (data.hasOwnProperty('judgments')) {
                obj['judgments'] = ApiClient.convertToType(data['judgments'], [JudgmentReport]);
            }
            if (data.hasOwnProperty('liens')) {
                obj['liens'] = ApiClient.convertToType(data['liens'], [LienReport]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PublicRecordsReport.ProviderEnum} provider
 */
PublicRecordsReport.prototype['provider'] = undefined;

/**
 * @member {Array.<module:model/BankruptcyReport>} bankruptcies
 */
PublicRecordsReport.prototype['bankruptcies'] = undefined;

/**
 * @member {Array.<module:model/JudgmentReport>} judgments
 */
PublicRecordsReport.prototype['judgments'] = undefined;

/**
 * @member {Array.<module:model/LienReport>} liens
 */
PublicRecordsReport.prototype['liens'] = undefined;





/**
 * Allowed values for the <code>provider</code> property.
 * @enum {String}
 * @readonly
 */
PublicRecordsReport['ProviderEnum'] = {

    /**
     * value: "EFX"
     * @const
     */
    "EFX": "EFX",

    /**
     * value: "TU"
     * @const
     */
    "TU": "TU",

    /**
     * value: "EXP"
     * @const
     */
    "EXP": "EXP",

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN"
};



export default PublicRecordsReport;

