/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RedirectViewServletContextServletRegistrations model module.
 * @module model/RedirectViewServletContextServletRegistrations
 * @version 1.0.0
 */
class RedirectViewServletContextServletRegistrations {
    /**
     * Constructs a new <code>RedirectViewServletContextServletRegistrations</code>.
     * @alias module:model/RedirectViewServletContextServletRegistrations
     */
    constructor() { 
        
        RedirectViewServletContextServletRegistrations.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RedirectViewServletContextServletRegistrations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RedirectViewServletContextServletRegistrations} obj Optional instance to populate.
     * @return {module:model/RedirectViewServletContextServletRegistrations} The populated <code>RedirectViewServletContextServletRegistrations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RedirectViewServletContextServletRegistrations();

            if (data.hasOwnProperty('mappings')) {
                obj['mappings'] = ApiClient.convertToType(data['mappings'], ['String']);
            }
            if (data.hasOwnProperty('runAsRole')) {
                obj['runAsRole'] = ApiClient.convertToType(data['runAsRole'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('className')) {
                obj['className'] = ApiClient.convertToType(data['className'], 'String');
            }
            if (data.hasOwnProperty('initParameters')) {
                obj['initParameters'] = ApiClient.convertToType(data['initParameters'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} mappings
 */
RedirectViewServletContextServletRegistrations.prototype['mappings'] = undefined;

/**
 * @member {String} runAsRole
 */
RedirectViewServletContextServletRegistrations.prototype['runAsRole'] = undefined;

/**
 * @member {String} name
 */
RedirectViewServletContextServletRegistrations.prototype['name'] = undefined;

/**
 * @member {String} className
 */
RedirectViewServletContextServletRegistrations.prototype['className'] = undefined;

/**
 * @member {Object.<String, String>} initParameters
 */
RedirectViewServletContextServletRegistrations.prototype['initParameters'] = undefined;






export default RedirectViewServletContextServletRegistrations;

