/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RedirectViewServletContextJspConfigDescriptorTaglibs model module.
 * @module model/RedirectViewServletContextJspConfigDescriptorTaglibs
 * @version 1.0.0
 */
class RedirectViewServletContextJspConfigDescriptorTaglibs {
    /**
     * Constructs a new <code>RedirectViewServletContextJspConfigDescriptorTaglibs</code>.
     * @alias module:model/RedirectViewServletContextJspConfigDescriptorTaglibs
     */
    constructor() { 
        
        RedirectViewServletContextJspConfigDescriptorTaglibs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RedirectViewServletContextJspConfigDescriptorTaglibs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RedirectViewServletContextJspConfigDescriptorTaglibs} obj Optional instance to populate.
     * @return {module:model/RedirectViewServletContextJspConfigDescriptorTaglibs} The populated <code>RedirectViewServletContextJspConfigDescriptorTaglibs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RedirectViewServletContextJspConfigDescriptorTaglibs();

            if (data.hasOwnProperty('taglibURI')) {
                obj['taglibURI'] = ApiClient.convertToType(data['taglibURI'], 'String');
            }
            if (data.hasOwnProperty('taglibLocation')) {
                obj['taglibLocation'] = ApiClient.convertToType(data['taglibLocation'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} taglibURI
 */
RedirectViewServletContextJspConfigDescriptorTaglibs.prototype['taglibURI'] = undefined;

/**
 * @member {String} taglibLocation
 */
RedirectViewServletContextJspConfigDescriptorTaglibs.prototype['taglibLocation'] = undefined;






export default RedirectViewServletContextJspConfigDescriptorTaglibs;

