/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RedirectViewServletContextSessionCookieConfig model module.
 * @module model/RedirectViewServletContextSessionCookieConfig
 * @version 1.0.0
 */
class RedirectViewServletContextSessionCookieConfig {
    /**
     * Constructs a new <code>RedirectViewServletContextSessionCookieConfig</code>.
     * @alias module:model/RedirectViewServletContextSessionCookieConfig
     */
    constructor() { 
        
        RedirectViewServletContextSessionCookieConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RedirectViewServletContextSessionCookieConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RedirectViewServletContextSessionCookieConfig} obj Optional instance to populate.
     * @return {module:model/RedirectViewServletContextSessionCookieConfig} The populated <code>RedirectViewServletContextSessionCookieConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RedirectViewServletContextSessionCookieConfig();

            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('secure')) {
                obj['secure'] = ApiClient.convertToType(data['secure'], 'Boolean');
            }
            if (data.hasOwnProperty('httpOnly')) {
                obj['httpOnly'] = ApiClient.convertToType(data['httpOnly'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('maxAge')) {
                obj['maxAge'] = ApiClient.convertToType(data['maxAge'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} domain
 */
RedirectViewServletContextSessionCookieConfig.prototype['domain'] = undefined;

/**
 * @member {Boolean} secure
 */
RedirectViewServletContextSessionCookieConfig.prototype['secure'] = undefined;

/**
 * @member {Boolean} httpOnly
 */
RedirectViewServletContextSessionCookieConfig.prototype['httpOnly'] = undefined;

/**
 * @member {String} name
 */
RedirectViewServletContextSessionCookieConfig.prototype['name'] = undefined;

/**
 * @member {String} path
 */
RedirectViewServletContextSessionCookieConfig.prototype['path'] = undefined;

/**
 * @member {String} comment
 */
RedirectViewServletContextSessionCookieConfig.prototype['comment'] = undefined;

/**
 * @member {Number} maxAge
 */
RedirectViewServletContextSessionCookieConfig.prototype['maxAge'] = undefined;






export default RedirectViewServletContextSessionCookieConfig;

