/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScoreReason model module.
 * @module model/ScoreReason
 * @version 1.0.0
 */
class ScoreReason {
    /**
     * Constructs a new <code>ScoreReason</code>.
     * @alias module:model/ScoreReason
     */
    constructor() { 
        
        ScoreReason.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScoreReason</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScoreReason} obj Optional instance to populate.
     * @return {module:model/ScoreReason} The populated <code>ScoreReason</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScoreReason();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('creditScoreFactorEffect')) {
                obj['creditScoreFactorEffect'] = ApiClient.convertToType(data['creditScoreFactorEffect'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
ScoreReason.prototype['code'] = undefined;

/**
 * @member {String} description
 */
ScoreReason.prototype['description'] = undefined;

/**
 * @member {String} creditScoreFactorEffect
 */
ScoreReason.prototype['creditScoreFactorEffect'] = undefined;






export default ScoreReason;

