/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrendedDataReport from './TrendedDataReport';

/**
 * The TrendedDataHistoryReport model module.
 * @module model/TrendedDataHistoryReport
 * @version 1.0.3
 */
class TrendedDataHistoryReport {
    /**
     * Constructs a new <code>TrendedDataHistoryReport</code>.
     * @alias module:model/TrendedDataHistoryReport
     */
    constructor() { 
        
        TrendedDataHistoryReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrendedDataHistoryReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrendedDataHistoryReport} obj Optional instance to populate.
     * @return {module:model/TrendedDataHistoryReport} The populated <code>TrendedDataHistoryReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrendedDataHistoryReport();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('trendedDataList')) {
                obj['trendedDataList'] = ApiClient.convertToType(data['trendedDataList'], [TrendedDataReport]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
TrendedDataHistoryReport.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/TrendedDataReport>} trendedDataList
 */
TrendedDataHistoryReport.prototype['trendedDataList'] = undefined;






export default TrendedDataHistoryReport;

