/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserRegReqDTO model module.
 * @module model/UserRegReqDTO
 * @version 1.0.0
 */
class UserRegReqDTO {
    /**
     * Constructs a new <code>UserRegReqDTO</code>.
     * @alias module:model/UserRegReqDTO
     * @param email {String} 
     * @param fname {String} 
     * @param lname {String} 
     * @param password {String} 
     * @param recoveryQuestion {Number} 
     * @param recoveryAnswer {String} 
     */
    constructor(email, fname, lname, password, recoveryQuestion, recoveryAnswer) { 
        
        UserRegReqDTO.initialize(this, email, fname, lname, password, recoveryQuestion, recoveryAnswer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, fname, lname, password, recoveryQuestion, recoveryAnswer) { 
        obj['email'] = email;
        obj['fname'] = fname;
        obj['lname'] = lname;
        obj['password'] = password;
        obj['recoveryQuestion'] = recoveryQuestion;
        obj['recoveryAnswer'] = recoveryAnswer;
    }

    /**
     * Constructs a <code>UserRegReqDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserRegReqDTO} obj Optional instance to populate.
     * @return {module:model/UserRegReqDTO} The populated <code>UserRegReqDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserRegReqDTO();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('mobile')) {
                obj['mobile'] = ApiClient.convertToType(data['mobile'], 'String');
            }
            if (data.hasOwnProperty('fname')) {
                obj['fname'] = ApiClient.convertToType(data['fname'], 'String');
            }
            if (data.hasOwnProperty('lname')) {
                obj['lname'] = ApiClient.convertToType(data['lname'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('recoveryQuestion')) {
                obj['recoveryQuestion'] = ApiClient.convertToType(data['recoveryQuestion'], 'Number');
            }
            if (data.hasOwnProperty('recoveryAnswer')) {
                obj['recoveryAnswer'] = ApiClient.convertToType(data['recoveryAnswer'], 'String');
            }
            if (data.hasOwnProperty('smsMsg')) {
                obj['smsMsg'] = ApiClient.convertToType(data['smsMsg'], 'Boolean');
            }
            if (data.hasOwnProperty('emailMsg')) {
                obj['emailMsg'] = ApiClient.convertToType(data['emailMsg'], 'Boolean');
            }
            if (data.hasOwnProperty('pushMsg')) {
                obj['pushMsg'] = ApiClient.convertToType(data['pushMsg'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
UserRegReqDTO.prototype['email'] = undefined;

/**
 * @member {String} mobile
 */
UserRegReqDTO.prototype['mobile'] = undefined;

/**
 * @member {String} fname
 */
UserRegReqDTO.prototype['fname'] = undefined;

/**
 * @member {String} lname
 */
UserRegReqDTO.prototype['lname'] = undefined;

/**
 * @member {String} password
 */
UserRegReqDTO.prototype['password'] = undefined;

/**
 * @member {Number} recoveryQuestion
 */
UserRegReqDTO.prototype['recoveryQuestion'] = undefined;

/**
 * @member {String} recoveryAnswer
 */
UserRegReqDTO.prototype['recoveryAnswer'] = undefined;

/**
 * @member {Boolean} smsMsg
 */
UserRegReqDTO.prototype['smsMsg'] = undefined;

/**
 * @member {Boolean} emailMsg
 */
UserRegReqDTO.prototype['emailMsg'] = undefined;

/**
 * @member {Boolean} pushMsg
 */
UserRegReqDTO.prototype['pushMsg'] = undefined;






export default UserRegReqDTO;

