/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserConfigDTO model module.
 * @module model/UserConfigDTO
 * @version 1.0.0
 */
class UserConfigDTO {
    /**
     * Constructs a new <code>UserConfigDTO</code>.
     * @alias module:model/UserConfigDTO
     */
    constructor() { 
        
        UserConfigDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserConfigDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserConfigDTO} obj Optional instance to populate.
     * @return {module:model/UserConfigDTO} The populated <code>UserConfigDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserConfigDTO();

            if (data.hasOwnProperty('theme')) {
                obj['theme'] = ApiClient.convertToType(data['theme'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('flags')) {
                obj['flags'] = ApiClient.convertToType(data['flags'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} theme
 */
UserConfigDTO.prototype['theme'] = undefined;

/**
 * @member {String} logo
 */
UserConfigDTO.prototype['logo'] = undefined;

/**
 * @member {Number} flags
 */
UserConfigDTO.prototype['flags'] = undefined;






export default UserConfigDTO;

