/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserOtpRespDTO model module.
 * @module model/UserOtpRespDTO
 * @version 1.0.0
 */
class UserOtpRespDTO {
    /**
     * Constructs a new <code>UserOtpRespDTO</code>.
     * @alias module:model/UserOtpRespDTO
     */
    constructor() { 
        
        UserOtpRespDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserOtpRespDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserOtpRespDTO} obj Optional instance to populate.
     * @return {module:model/UserOtpRespDTO} The populated <code>UserOtpRespDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserOtpRespDTO();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('passcode')) {
                obj['passcode'] = ApiClient.convertToType(data['passcode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
UserOtpRespDTO.prototype['key'] = undefined;

/**
 * @member {String} passcode
 */
UserOtpRespDTO.prototype['passcode'] = undefined;






export default UserOtpRespDTO;

