/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserRenewOtpReqDTO model module.
 * @module model/UserRenewOtpReqDTO
 * @version 1.0.0
 */
class UserRenewOtpReqDTO {
    /**
     * Constructs a new <code>UserRenewOtpReqDTO</code>.
     * @alias module:model/UserRenewOtpReqDTO
     * @param key {String} 
     */
    constructor(key) { 
        
        UserRenewOtpReqDTO.initialize(this, key);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key) { 
        obj['key'] = key;
    }

    /**
     * Constructs a <code>UserRenewOtpReqDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserRenewOtpReqDTO} obj Optional instance to populate.
     * @return {module:model/UserRenewOtpReqDTO} The populated <code>UserRenewOtpReqDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserRenewOtpReqDTO();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
UserRenewOtpReqDTO.prototype['key'] = undefined;






export default UserRenewOtpReqDTO;

