/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserNotificationsPref model module.
 * @module model/UserNotificationsPref
 * @version 1.0.0
 */
class UserNotificationsPref {
    /**
     * Constructs a new <code>UserNotificationsPref</code>.
     * @alias module:model/UserNotificationsPref
     */
    constructor() { 
        
        UserNotificationsPref.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserNotificationsPref</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserNotificationsPref} obj Optional instance to populate.
     * @return {module:model/UserNotificationsPref} The populated <code>UserNotificationsPref</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserNotificationsPref();

            if (data.hasOwnProperty('smsMsg')) {
                obj['smsMsg'] = ApiClient.convertToType(data['smsMsg'], 'Boolean');
            }
            if (data.hasOwnProperty('emailMsg')) {
                obj['emailMsg'] = ApiClient.convertToType(data['emailMsg'], 'Boolean');
            }
            if (data.hasOwnProperty('pushMsg')) {
                obj['pushMsg'] = ApiClient.convertToType(data['pushMsg'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} smsMsg
 */
UserNotificationsPref.prototype['smsMsg'] = undefined;

/**
 * @member {Boolean} emailMsg
 */
UserNotificationsPref.prototype['emailMsg'] = undefined;

/**
 * @member {Boolean} pushMsg
 */
UserNotificationsPref.prototype['pushMsg'] = undefined;






export default UserNotificationsPref;

