/**
 * StitchCredit API
 * StitchCredit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserOtpReqDTO model module.
 * @module model/UserOtpReqDTO
 * @version 1.0.0
 */
class UserOtpReqDTO {
    /**
     * Constructs a new <code>UserOtpReqDTO</code>.
     * @alias module:model/UserOtpReqDTO
     * @param key {String} 
     * @param code {String} 
     */
    constructor(key, code) { 
        
        UserOtpReqDTO.initialize(this, key, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, code) { 
        obj['key'] = key;
        obj['code'] = code;
    }

    /**
     * Constructs a <code>UserOtpReqDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserOtpReqDTO} obj Optional instance to populate.
     * @return {module:model/UserOtpReqDTO} The populated <code>UserOtpReqDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserOtpReqDTO();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
UserOtpReqDTO.prototype['key'] = undefined;

/**
 * @member {String} code
 */
UserOtpReqDTO.prototype['code'] = undefined;






export default UserOtpReqDTO;

